### ISSUE TITLE
My container donot auto Keep monitoring for local and remote changes

### ISSUE THREAD

**Issue by fusang1337** [crocandr/docker-onedrive#2]
I try do this ,but it don`t work 
```
Application has been successfully authorised, however no additional command switches were provided.

Please use --help for further assistance in regards to running this application.

[root@00fcc1cb6a60 /]# systemctl --user enable onedrive
Created symlink /root/.config/systemd/user/default.target.wants/onedrive.service → /usr/lib/systemd/user/onedrive.service.
[root@00fcc1cb6a60 /]# systemctl --user start onedrive
**Failed to connect to bus: No such file or directory**
[root@00fcc1cb6a60 /]# onedrive -m
Configuration file successfully loaded
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
3600
```

**Comment by fusang1337** [comment]
docker run -tid --name onedrive --restart always --privileged  -v /root/config/onedirve/config:/config -v /mnt/nas/file/verysync:/onedrive croc/onedrive

**Comment by crocandr** [comment]
Sorry, I don't understand your problem fully, but maybe these help a little:
- do not step in the container, you can't use systemctl and another "normal Linux" command too, this is not a virtual machine, use the container management (start, restart, recreate, configure, etc...)
- You should wait some minutes (1-10mins), if you have lots of data on Onedrive Cloud, the client first sync start happens very slowly
- try the docker-compose method if you can, maybe it is easier to configure

Sorry, this is just a container for Onedrive Linux package. I'm not a onedrive app programmer. :(

I have given up the Onedrive usage in Linux because the support is not fully and 100% stable. The clients (other containers, like https://hub.docker.com/r/driveone/onedrive) or native Onedrive client Linux packages not working reliably in long term. So I changed another Cloud Provider or just use for backup with duplicaty/dupliciti. Sorry.

Have a nice day!

**Comment by fusang1337** [comment]
thinks!
